backend:
  name: git-gateway
  repo: midtownrulers/playbook
  branch: main

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads
display_url: "https://playbook.midtownrulers.org"
logo_url: "https://playbook.midtownrulers.org/img/logo.png"


collections:
- name: docs
  label: "Docs"
  folder: docs
  nested:
    depth: 100
  identifier_field: title
   meta: { path: { label: Parent, widget: parent, index_file: 'index' } }
  extension: md
  widget: "list"
  create: true
  slug: "{{fields.slug}}"
  fields:
    - { name: paths, label: Path, widget: string }
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
- name: categories
  label: "Categories"
  folder: docs
  identifier_field: label
  widget: list
  create: true
  extension: yml
  path: '{{fields.slug}}/'
  filename: '_category_'
  fields:
    - { name: label, label: Title, widget: string }
    - { name: slug, label: Slug, widget: string }
