name: Typesense scraper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scraper:
      name: scraper
      runs-on: ubuntu-latest
      env:
        TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
        TYPESENSE_HOST: ${{ secrets.TYPESENSE_API_KEY }}
        TYPESENSE_PORT: ${{ secrets.TYPESENSE_PORT }}
        TYPESENSE_PROTOCOL: ${{ secrets.TYPESENSE_PROTOCOL }} 
        CONFIG: '$(cat typesense.config.json | jq -r tostring)'
      container: 
        image: typesense/docsearch-scraper:latest
        options: -e TYPESENSE_API_KEY -e TYPESENSE_PORT -e TYPESENSE_PROTOCOL -e CONFIG
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
        - name: ls
          run: ls
        - name: ls root
          run: ls /root
        - name: ls src
          run: ls ./src/
          

