name: Typesense scraper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    scraper:
        name: scraper
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run DocSearch Scraper
            uses: celsiusnarhwal/typesense-scraper@v2
            with:
              api-key: ${{ secrets.TYPESENSE_API_KEY }}
              host: ${{ secrets.TYPESENSE_HOST }}
              port: 443
              protocol: https
              config: typesense.config.json 
